### ISSUE TITLE
can we change cartridge hex colours from BBGGRR to RRGGBB?

### ISSUE THREAD

**Issue by spacebake** [spacebake/Loungeware#115]
RRGGBB is a much more common way of writing hex colour. Even gamemaker's sprite editor uses rrggbb.
is there any reason we can't do this @torontofangirl ?

**Comment by torontofangirl** [comment]
i thought it would be good to be consistent with gm

**Comment by bakumoe** [comment]
after many failed attempts, yes it turns out we could change it from BGR to RGB :>
