### ISSUE TITLE
Larold indexing rapid expansion 

### ISSUE THREAD

**Issue by net8floz** [spacebake/Loungeware#118]
1) Array of larold credits needs to be moved to it's own file 
2) Array of larolds should expand to a tuple of [larold name, authorname] 

example:

var larolds = [ 
   ["funky booty larold", "bakusaii"]
];

**Comment by spacebake** [comment]
now i wanna see funky booty larold

**Comment by NuxiiGit** [comment]
how does this work now, with the larold database?

**Comment by spacebake** [comment]
i think this is basically solved now with the new system kindly made by meseta
