### ISSUE TITLE
macros for no no functions

### ISSUE THREAD

**Issue by torontofangirl** [spacebake/Loungeware#159]
example:
```js
#macro audio_play_sound __throw_sound
#macro space_approved_play_sound audio_play_sound
function __throw_sound() {
  throw "use sfx_play";
}
```
notes:
seperate function for each not allowed function so you can pass arguments without meaning anything

any objections?

**Comment by NuxiiGit** [comment]
if we do this, make sure to update all references in the core code as well

**Comment by torontofangirl** [comment]
moved to #161
