### ISSUE TITLE
Gallery Text Highlighting is off On Desktop

### ISSUE THREAD

**Issue by Kilomatter** [spacebake/Loungeware#213]
The highlighted text is one below the selected game, and the first game in the list is colored in black.
This issue is unique to the desktop build. It does not appear on HTML5. 

![image](https://user-images.githubusercontent.com/74310019/147832676-f0954804-d2e3-48ce-85d1-eaf976fb16c0.png)

It looks slightly different when selecting the games at the beginning and end of the list:

![image](https://user-images.githubusercontent.com/74310019/147832845-6e165e64-9ce8-4aab-b0e0-53283b977318.png)
![image](https://user-images.githubusercontent.com/74310019/147832856-8d972d48-32eb-49a4-a6db-59173afae941.png)

**Comment by torontofangirl** [comment]
fixed in #214
