### ISSUE TITLE
Delay before PROMPT macro actually returns the prompt

### ISSUE THREAD

**Issue by bakumoe** [spacebake/Loungeware#50]
The PROMPT macro returns an empty string, instead of a string containing the prompt, until the first step event in your game's room.

This is kinda janky for games that use array prompts and have to do some sort of setup depending on the prompt, as they'd have to run that code once in step instead of create/room_start :/

![image](https://user-images.githubusercontent.com/1330101/126027005-2c1f52a8-96f7-4d5b-a1d5-024fc8c4ac32.png)

**Comment by spacebake** [comment]
forgot to close this. it was fixed at some point uwuwuwuwu
