### ISSUE TITLE
Escape should be able to be used to exit the gallery

### ISSUE THREAD

**Issue by NuxiiGit** [spacebake/Loungeware#58]
Just like Enter can be used to select menu items, Escape should be able to be used to exit a sub-menu. This would work just like how pausing uses Escape.

**Comment by Mega-Baboon** [comment]
yes

**Comment by spacebake** [comment]
agree. the reason it doesn't currently is because both ESC and Enter are the same button (___KEY_PAUSE), and it'd be weird if enter also took you back. 
could hard code it, though.

**Comment by spacebake** [comment]
resolved by zandy bo bandy. what a champ
