### ISSUE TITLE
Evil asset names

### ISSUE THREAD

**Issue by bakumoe** [spacebake/Loungeware#68]
absolutely disgraceful 😔

![image](https://user-images.githubusercontent.com/1330101/128954088-740572a7-fc8c-49bf-b0e8-9761c5ca2699.png)
![image](https://user-images.githubusercontent.com/1330101/128954111-5e31b1bd-6dfc-41d6-8c14-913efd268143.png)

**Comment by spacebake** [comment]
fixed 😳
