### ISSUE TITLE
Dev Config Refactor

### ISSUE THREAD

**Issue by net8floz** [spacebake/Loungeware#73]
As a new developer I want to be able to easily get involved with making microgames and not have to deal with setting up a external json file for testing my games. I want to be able to use in-game commands or menus to enter dev mode and to select a particular game to test. 

As a git maintainer I want to ensure that devs are able to set up different configurations without bogging down git history or creating conflicts. Common pitfalls include registering in-ide configs and git ignored configs in included files. 

Prerequisite is that in the game now there is a concept of a "Shipping" macro config, this is what we use in game to disable dev only menus or features from final shipping builds and should be used here. 

Prerequisite it is possible to figure out if the user is IN IDE by parsing the process arguments for -game. 

The solution looks like this: 
- Creating a boot screen that runs if we know the user is A) Not running a shipping build and B) in the ide. This boot screen will ask to run the normal game, or enter dev config. 
- If enter dev config you are taken to a menu that allows you to enable or disable dev mode ( checkbox ) and select a game. A select widget will need to be created for this that displays all games. Function before form here. 
- When dev config is applied this creates a save file in AppData and game restarts 

If dev mode is enabled
- Game now boots into test mode. It is possible to once again enter the dev menu from the previous steps by pressing some function key ( you choose ) 
- Test mode runs as we're all familiar with, loop selected game forever 

If dev mode is not enabled
- Game boots back into selection menu from the first steps. But again, only if in ide and only if not shipping build. 

All these ideas allow the new developer to be mostly hands off on configuration, and they just need to interact with menus.

**Comment by spacebake** [comment]
it's britney bitch!
