### ISSUE TITLE
Demo game

### ISSUE THREAD

**Issue by net8floz** [spacebake/Loungeware#74]
Hey what about a demo game that has the absolute bare minimum set up to be a game. some simple press one button thing. this can be the game we point to that has very verbose commenting and all the basic functionality one would expect to need examples for.

**Comment by net8floz** [comment]
Including stuff like being the source template for microgame data ( enabled off ), cartridge sprites,

**Comment by torontofangirl** [comment]
you should make a video of setting up a microgame

**Comment by torontofangirl** [comment]
done
