### ISSUE TITLE
Remove "Packages" section from the project

### ISSUE THREAD

**Issue by NuxiiGit** [spacebake/Loungeware#86]
Not needed

![image](https://user-images.githubusercontent.com/39774219/129605642-cff0c5cb-a035-48bd-8f25-9862eace11f1.png)

**Comment by NuxiiGit** [comment]
It should probably look like this:

![image](https://user-images.githubusercontent.com/39774219/129605803-5ae15a8d-f943-4ebc-836b-4f0e4a043a65.png)

**Comment by spacebake** [comment]
what is this exactly? ive never seen these checkboxes in my life
