### ISSUE TITLE
every metadata should be in it's own script 

### ISSUE THREAD

**Issue by torontofangirl** [spacebake/Loungeware#87]

**Comment by net8floz** [comment]
@spacebake is it a requirement?

**Comment by spacebake** [comment]
i think it's probably easier explained to people that way, but it's not an absolute requirement. maybe we could just have the docs make a new file but in reality it doesnt actually matter, they can do it either way

**Comment by spacebake** [comment]
i don't think we're doing this any more. closing for now.
