### ISSUE TITLE
Game window should not hide the cursor

### ISSUE THREAD

**Issue by Pizzaandy** [spacebake/Loungeware#94]
It's annoying, especially on the HTML version.
We should either:
a) Remove this behavior entirely
b) Only hide the cursor on fullscreen

**Comment by NuxiiGit** [comment]
is it possible to change the "hide cursor" state? i thought that was a global game option?

**Comment by net8floz** [comment]
Perhaps it'd be cooler to make a block pixelated cursor instead?

**Comment by NuxiiGit** [comment]
looks like `cr_none` is a constant, who would've thought

i could work on this issue, setting the cursor to `cr_none` when in full screen, and to `cr_normal` when not
